version: '3.4'

services:
  telegram_notification_bot:
    image: telegram_notification_bot
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8002:8002
    env_file:
      - docker.env
    volumes:
      - ./data_base/sql_app.db:/app/data_base/sql_app.db
volumes:
  db: