version: '3.4'

services:
  telegram_notification_bot:
    image: telegram_notification_bot
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8002:8002
    env_file:
      - .env
    volumes:
      - ./database/sql_app.db:/database/sql_app.db
